name: 05 - Update Api

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-api-*

env:
  CHUNK_SIZE: 20
  FIRST_CHUNK_SIZE: 40
  ALIAS: ART
  COUNTRY_CODE: ${{ github.event.client_payload.country_code }}
  LIST_LANGUAGE_CODE: ${{ github.event.client_payload.list_language_code }}
  LIST_CATEGORY_CODE: ${{ github.event.client_payload.list_category_code }}

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout crawl
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/nodejs-clutter
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.GH_PAT }}
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/${{ env.COUNTRY_CODE }}-data
          path: src/databases/data
          token: ${{ secrets.GH_PAT }}

      - name: Checkout api
        uses: actions/checkout@v4
        with:
          repository: CltnApi/${{ env.COUNTRY_CODE }}
          path: apidata
          token: ${{ secrets.GH_PAT }}
          ref: gh-pages

      - name: Init Api
        run: |
          IFS=',' read -ra ARRAY_CATEGORY_CODE <<<"$LIST_CATEGORY_CODE"
          IFS=',' read -ra ARRAY_LANGUAGE_CODE <<<"$LIST_LANGUAGE_CODE"

          for LANGUAGE_CODE in "${ARRAY_LANGUAGE_CODE[@]}"; do
            export LANGUAGE_CODE=$LANGUAGE_CODE
            for CATEGORY_CODE in "${ARRAY_CATEGORY_CODE[@]}"; do
              export CATEGORY_CODE=$CATEGORY_CODE
              node src/api/update_api.js
            done
          done

      - name: Push
        working-directory: apidata
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m ':white_check_mark: Update Api'
          git push origin ${{ matrix.language_code }} -f
